Feature/logic get all job title
The-Cupcake-team/Jobs-finder pull request #12
Opened 2023-06-04 11:25 UTC by Hasa9nAli

Hi Dear Beautiful Reviewer this is our branch we 
1 - fix some bugs 
2-  add logic to GetAllJobTitleUseCase 
3 - add the Repository Provider
4 - add launch to test the data 
use fetch data from Api you need just call viewModel of Job in any Activity or fragment and watch Logcat then you will see amazing result 
thank you for you effort ( your colleagues @Hasa9nAli , @abuhussien28 )

2023-06-04 20:37 UTC, AmeerAmjed requested changes

2023-06-04 20:37 UTC, AmeerAmjed commented on app/src/main/java/com/cupcake/jobsfinder/data/repository/Repository.kt
> +  suspend fun getAllJobTitles():Flow<List<JobTitleDto>>
no need Flow is useless use **suspend** it's enough.

2023-06-04 20:37 UTC, AmeerAmjed commented on app/src/main/java/com/cupcake/jobsfinder/data/repository/RepositoryImpl.kt
> +	override suspend fun getAllJobTitles(): Flow<List<JobTitleDto>> {
this function need refactor

2023-06-04 20:37 UTC, AmeerAmjed commented on app/src/main/java/com/cupcake/jobsfinder/di/RepositoryModule.kt
> +    companion object {
delete this function no need

2023-06-04 20:37 UTC, AmeerAmjed commented on app/src/main/java/com/cupcake/jobsfinder/domain/usecase/GetAllJobTitleUseCase.kt
> +    suspend operator fun invoke()
function neeed improve

2023-06-05 12:59 UTC, TarekIdrees requested changes

2023-06-05 12:59 UTC, TarekIdrees commented on app/src/main/java/com/cupcake/jobsfinder/ui/jobs/JobsViewModel.kt
> +    private val repository: RepositoryImpl
Why did you inject repo impl in ViewModel ?

2023-06-05 14:49 UTC, mustafa-sab3alarab approved these changes
just change ameer's requests

2023-06-05 14:55 UTC, abuhussien28 commented on app/src/main/java/com/cupcake/jobsfinder/data/repository/RepositoryImpl.kt
> +	override suspend fun getAllJobTitles(): Flow<List<JobTitleDto>> {
done

2023-06-05 14:55 UTC, AbuHussien28 commented on app/src/main/java/com/cupcake/jobsfinder/data/repository/Repository.kt
> +  suspend fun getAllJobTitles():Flow<List<JobTitleDto>>
done

2023-06-05 15:13 UTC, AbuHussien28 commented on app/src/main/java/com/cupcake/jobsfinder/di/RepositoryModule.kt
> +    companion object {
done

2023-06-05 15:17 UTC, abuhussien28 commented on app/src/main/java/com/cupcake/jobsfinder/domain/usecase/GetAllJobTitleUseCase.kt
> +    suspend operator fun invoke()
done

2023-06-05 15:18 UTC, AbuHussien28 commented on app/src/main/java/com/cupcake/jobsfinder/ui/jobs/JobsViewModel.kt
> +    private val repository: RepositoryImpl
can for test and we forget to remove it 
now we remove it

2023-06-05 18:12 UTC, AmeerAmjed approved these changes
good job

2023-06-05 18:18 UTC, merged