feature/get-posts
The-Cupcake-team/Jobs-finder pull request #14
Opened 2023-06-04 14:09 UTC by Belal-Alkhatib

- refactor `PostDto `class to make the field nullable
- refactor api call function `getAllPosts()` to return `Response<BaseResponse<List<PostDto>>>`
- delete fake data and using a real api request
- create `wrapFlowResponseWithErrorHandler` to handel the requests that return a flow
- refactor `PostsViewModel` by split the state implement function to supfunction
- use `CoroutineExceptionHandler` to handel the coroutine exception

@davidsamuelx 
@Belal-Alkhatib

2023-06-04 15:55 UTC, mustafa-sab3alarab commented on app/src/main/java/com/cupcake/jobsfinder/data/remote/JobApiService.kt
> +    suspend fun getAllPosts(): Response<BaseResponse<List<PostDto>>>
rename it to getPosts

2023-06-04 17:33 UTC, mustafa-sab3alarab commented on app/src/main/java/com/cupcake/jobsfinder/data/repository/Repository.kt
>    suspend fun getAllPosts(): Flow<List<PostDto>>
useless because it's only one response,
you can see video number 0247.

2023-06-04 17:34 UTC, mustafa-sab3alarab commented on app/src/main/java/com/cupcake/jobsfinder/data/repository/RepositoryImpl.kt
> +		return flow {
you emit only the value!

2023-06-04 19:23 UTC, mustafa-sab3alarab requested changes
and also put repository interface in domain layer

2023-06-04 20:48 UTC, AmeerAmjed requested changes

2023-06-04 20:48 UTC, AmeerAmjed commented on app/src/main/java/com/cupcake/jobsfinder/ui/posts/PostsViewModel.kt
> -            id = this.id,
no need use this

2023-06-04 20:48 UTC, AmeerAmjed commented on app/src/main/java/com/cupcake/jobsfinder/ui/posts/PostsViewModel.kt
>      private val _errors: MutableList<ErrorUIState> = mutableListOf()
this line no error should in uistate class

2023-06-05 12:52 UTC, TarekIdrees approved these changes

2023-06-05 14:44 UTC, mustafa-sab3alarab approved these changes

2023-06-05 18:23 UTC, AmeerAmjed requested changes

2023-06-05 18:23 UTC, AmeerAmjed commented on app/src/main/java/com/cupcake/jobsfinder/domain/model/Post.kt
Should be  field in domain model no nullable

2023-06-05 18:23 UTC, AmeerAmjed commented on app/src/main/java/com/cupcake/jobsfinder/ui/posts/PostUIState.kt
> +fun Post.toPostItemUIState(): PostItemUIState {
move check nullable to mapper in domain

2023-06-05 18:38 UTC, AmeerAmjed approved these changes

2023-06-05 18:52 UTC, merged