Feature/create job
The-Cupcake-team/Jobs-finder pull request #4
Opened 2023-05-31 07:05 UTC by AmeerAmjed

Handel :- 
1- Create function **createJob** in **api service**.
2- Create function createJob in **repository** and implement in **RepositoryImpl**.
3- Create usecase **CreateJobUseCase**.
4- Create state  **CreateJobUiState** and **JobFormUiState**.
5- Create CreateJobViewModel.

2023-05-31 09:39 UTC, mustafa-sab3alarab commented on app/src/main/java/com/cupcake/jobsfinder/domain/useCase/CreateJobUseCase.kt
> +    private val repository: RepositoryImpl
use repository interface

2023-05-31 09:48 UTC, mustafa-sab3alarab commented on app/src/main/java/com/cupcake/jobsfinder/domain/useCase/CreateJobUseCase.kt
> +    data class ParamJobInfo(
put it in model folder

2023-05-31 09:52 UTC, mustafa-sab3alarab commented on app/src/main/java/com/cupcake/jobsfinder/ui/create_job/CreateJobViewModel.kt
> +    val jobUiState = _jobUiState.asStateFlow()
Why are you casting here?

2023-05-31 10:02 UTC, mustafa-sab3alarab requested changes
Edit the first review 🗡️

2023-06-02 16:06 UTC, mustafa-sab3alarab approved these changes

2023-06-02 16:06 UTC, mustafa-sab3alarab approved these changes

2023-06-02 17:22 UTC, TarekIdrees approved these changes

2023-06-02 21:18 UTC, merged