Feature/add image to post
The-Cupcake-team/Jobs-finder pull request #46
Opened 2023-06-19 19:05 UTC by Hasa9nAli

hello dears  reviewers this new branch to add new image  i work on 
1- change button to spinner 
2- get image from camera using (Dexter)
3 - get image from gallery using (Dexter)
4- add image to screen and cancel image from screen

2023-06-20 19:24 UTC, AmeerAmjed requested changes

2023-06-20 19:24 UTC, AmeerAmjed commented on presentation/ui/src/main/java/com/cupcake/ui/post/CreatePostFragment.kt
> +                    Snackbar.make(requireView(), "Post Created Successfully", Snackbar.LENGTH_LONG)
why string hardCode

2023-06-20 19:24 UTC, AmeerAmjed commented on presentation/ui/src/main/java/com/cupcake/ui/post/CreatePostFragment.kt
> +        Dexter.withContext(this.requireContext()).withPermissions(
handle permissions with use plugin

2023-06-20 19:24 UTC, AmeerAmjed commented on presentation/ui/src/main/java/com/cupcake/ui/post/CreatePostFragment.kt
> +    companion object {
why **companion object**  not private

2023-06-20 19:24 UTC, AmeerAmjed commented on presentation/ui/src/main/res/drawable/cancal_icon.xml
why no following naming icon should name as ic_cancal

2023-06-20 19:56 UTC, Hasa9nAli commented on presentation/ui/src/main/java/com/cupcake/ui/post/CreatePostFragment.kt
> +                    Snackbar.make(requireView(), "Post Created Successfully", Snackbar.LENGTH_LONG)
not me work on the this code this is for previous person but  i will fix it thank you for you notice

2023-06-21 10:28 UTC, Hasa9nAli commented on presentation/ui/src/main/java/com/cupcake/ui/post/CreatePostFragment.kt
> +        Dexter.withContext(this.requireContext()).withPermissions(
Done

2023-06-22 09:53 UTC, TarekIdrees requested changes

2023-06-22 09:53 UTC, TarekIdrees commented on presentation/ui/src/main/java/com/cupcake/ui/post/CreatePostFragment.kt
> +        binding.buttonCamera.setOnClickListener {
separate each button click in function

2023-06-22 10:41 UTC, merged