Feature/home screen
The-Cupcake-team/Jobs-finder pull request #51
Opened 2023-06-21 12:43 UTC by abdallahFc

#### Description

> This pull request to refactor home screen and add comment screen.

2023-06-21 19:49 UTC, mustafa-sab3alarab commented on presentation/viewmodels/src/main/java/com/cupcake/viewmodels/comment/CommentViewModel.kt
> +                error = null,
why assign null to an error when it's already null

2023-06-21 19:51 UTC, mustafa-sab3alarab commented on presentation/viewmodels/src/main/java/com/cupcake/viewmodels/posts/PublicPostsViewModel.kt
> +                isError = false,
the same here it's has a default value

2023-06-21 19:51 UTC, mustafa-sab3alarab requested changes
well job

2023-06-21 20:11 UTC, mustafa-sab3alarab approved these changes

2023-06-21 20:11 UTC, mustafa-sab3alarab approved these changes

2023-06-21 20:16 UTC, mustafa-sab3alarab approved these changes

2023-06-22 09:55 UTC, TarekIdrees requested changes

2023-06-22 09:55 UTC, TarekIdrees commented on data/repository/src/main/java/com/cupcake/repository/JobFinderRepositoryImpl.kt
> +        val fakePosts = listOf(
is this fake data still here?

2023-06-22 11:51 UTC, merged