get all jobs
The-Cupcake-team/Jobs-finder pull request #8
Opened 2023-05-31 18:24 UTC by mustafa-sab3alarab

get all jobs and handle jobs screen ui state

2023-05-31 20:09 UTC, AmeerAmjed requested changes

2023-05-31 20:09 UTC, AmeerAmjed commented on app/src/main/java/com/cupcake/jobsfinder/data/remote/BaseResponse.kt
can use @Serializable with data class no need use **SerializedName** annotation to all fields

2023-05-31 20:09 UTC, AmeerAmjed commented on app/src/main/java/com/cupcake/jobsfinder/data/remote/response/job/JobDto.kt
can use @serializable with data class no need use SerializedName annotation to all fields

2023-05-31 20:09 UTC, AmeerAmjed commented on app/src/main/java/com/cupcake/jobsfinder/data/repository/Repository.kt
in Repository return data fom dto form response in data layer

2023-05-31 20:09 UTC, AmeerAmjed commented on app/src/main/java/com/cupcake/jobsfinder/domain/usecase/GetAllJobUseCase.kt
where is mapper to **dto** to domain model

2023-06-02 05:34 UTC, AmeerAmjed approved these changes

2023-06-02 17:25 UTC, TarekIdrees approved these changes

2023-06-02 21:32 UTC, merged